global:
  scrape_interval: 1m

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 1m
  #   static_configs:
  #     - targets: ['localhost:9090']

  # - job_name: 'aisystem'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['aisystem:9090']

  - job_name: 'pushgateway'
    scrape_interval: 1s
    # honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  
