version: '3.8'

networks:
  monitoring:
    driver: bridge
    
x-platform: &default-platform linux/amd64

services:
  aisystem:
    build:
      dockerfile: ./Dockerfile
      args:
        - MODE=CPU
    container_name: aisystem
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - monitoring
    environment:
      - DEVICE=cpu
      - VIDEO_PATH=rtsp://admin:@192.168.2.245:554
    platform: *default-platform