name: pytorch
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - uvicorn
  - gunicorn
  - opencv
  - tensorboard
  - pip
  - pip:
    - -r requirements.txt