name: pytorch
dependencies:
  - python=3.8
  - pytorch::pytorch
  - pytorch::torchvision
    #- pytorch::pytorch-cuda=11.8
  - uvicorn
  - gunicorn
  - tensorboard
  - prometheus_client
  - pip
  - pip:
    - -r requirements.txt
